### ISSUE TITLE
Re-Organize mnist code into package, module(s) + class

### ISSUE THREAD

**Issue by dadamsncsa** [nanoMFG/python-best-practices-v2#81]
## Summary
Re-tool existing solution code to state that can demonstrate best practice principles we are trying to show.

### Part 1 Directory structure and filenames
```
|---digit_reader/
|   |---__init__.py
|   |---model/
|   |   |---__init__.py
|   |   |---model.py
|   |   |---helpers.py
```
### Part 2 :Code changes
- [x] Rename `mnist_convnet.py` -> `digit_reader/model/model.py
- [x] Add file: `digit_reader/model/helpers.py`
- [x] Move `prepare_data` function to helpers
- [x] Create class and add remaining remaining functions as methods.  Class name could be called Convnet or MnistModel, or something...

**Comment by dadamsncsa** [comment]
Hey,  I was thinking we should add `/src` directory.  After reading a bit here:
https://docs.pytest.org/en/stable/goodpractices.html#choosing-a-test-layout-import-rules  
and  here  
https://blog.ionelmc.ro/2014/05/25/python-packaging/#the-structure  

I kind of wanted to have a `/src` from the beginning because it helps when deploying to nanoHUB.  Also it is more standard across other languages.
